version: '3.7'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - APP_DB_NAME=main
    ports:
      - '5432:5432'

  accounts:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db